export default {
    en: {
        address: 'Address',
        addresses: 'Addresses',
        addressLine2: 'Comment or notes for delivery',
        cancel: 'Cancel',
        changePassword: 'Change Password',
        city: 'City',
        confirmPassword: 'Confirm New Password',
        country: 'Country',
        delete: 'Delete',
        deleteAddress: 'Delete Address',
        deleteAddressConfirm: 'Are you sure you want to delete the address?',
        details: 'Details',
        edit: 'Edit',
        editAddress: 'Edit Address',
        editDetails: 'Edit Details',
        email: 'Email',
        fieldRequired: 'This field is required',
        name: 'Full Name',
        newAddress: 'New Address',
        newPassword: 'New Password',
        oldPassword: 'Old Password',
        passwordMismatch: 'Passwords don\'t match',
        phoneNumber: 'Phone Number',
        postalCode: 'Postal Code',
        save: 'Save',
        state: 'State',
        title: 'My Account',
        update: 'Update',
        dni: 'Identification Number',
        vatLabel: 'ID'

    },
    es: {
        address: 'Dirección',
        addresses: 'Direcciones',
        addressLine2: 'Comentario para el delivery',
        cancel: 'Cancelar',
        changePassword: 'Cambiar contraseña',
        city: 'Ciudad',
        confirmPassword: 'Confirmar contraseña nueva',
        country: 'País',
        delete: 'Eliminar',
        deleteAddress: 'Eliminar dirección',
        deleteAddressConfirm: 'Está seguro que desea eliminar esta dirección?',
        details: 'Detalles',
        edit: 'Editar',
        editAddress: 'Editar dirección',
        editDetails: 'Editar detalles',
        email: 'E-Mail',
        fieldRequired: 'Este campo es obligatorio',
        name: 'Nombre Completo',
        newAddress: 'Actualizar dirección',
        newPassword: 'Contraseña nueva',
        oldPassword: 'Contraseña antigua',
        passwordMismatch: 'Las contraseñas no coinciden',
        phoneNumber: 'Número de teléfono',
        postalCode: 'Código Postal',
        save: 'Guardar',
        state: 'Estado/Provincia',
        title: 'Mi cuenta',
        update: 'Actualizar',
        dni: 'Número de Documento de Identidad',
        vatLabel: 'DNI'
    }
};
