export default {
    en: {
        back: 'Back',
        category: 'Category',
        collection: 'Collection',
        delete: 'Delete',
        description: 'Description',
        enabled: 'Enabled',
        fieldRequired: 'This field is required',
        homepage: 'Homepage',
        homepageFeatured: 'Homepage Featured',
        mainNavigation: 'Main Navigation',
        name: 'Name',
        parent: 'Parent Collection',
        save: 'Save',
        sections: 'Featured in Sections',
        title: 'Edit Collection',
        type: 'Type',
        deleteCollectionModalTitle: 'You confirme the deletion?',
    },
    es: {
        back: 'Volver',
        category: 'Categoría',
        collection: 'Colección',
        delete: 'Remover',
        description: 'Descripción',
        enabled: 'Activada',
        fieldRequired: 'Este campo es obligatorio',
        homepage: 'Página Principal',
        homepageFeatured: 'Destacados de Página Principal',
        mainNavigation: 'Menu Principal',
        name: 'Nombre',
        parent: 'Colección Base',
        save: 'Guardar',
        sections: 'Destacados en Secciones',
        title: 'Editar Colección',
        type: 'Tipo',
        deleteCollectionModalTitle: 'Desea confirmar la eliminacion?',
    }
};
