export default {
    en: {
        add: 'Add',
        cancel: 'Cancel',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'This field is required',
        name: 'Name',
        type: 'Type',
        category: 'Category',
        collection: 'Collection',
        enabledHeading: 'Enabled',
        homepage: 'Homepage',
        homepageFeatured: 'Homepage Featured',
        mainNavigation: 'Main Navigation',
        nameHeading: 'Name',
        new: 'New',
        newModalTitle: 'Add new collection',
        parentHeading: 'Parent Collection',
        tagsHeading: 'Tags',
        title: 'Collections',
        translationsHeading: 'Translations',
        noResults: 'No collections yet',
        subtitle: 'Subtitulo',
        content1: 'Esto es lo que hacemos: bla bla bla',
    },
    es: {
        category: 'Categoría',
        collection: 'Colecciones',
        enabledHeading: 'Activada',
        homepage: 'Página Principal',
        homepageFeatured: 'Destacados en Página Principal',
        mainNavigation: 'Menú Principal',
        nameHeading: 'Nombre',
        new: 'Nuevo',
        noResults: 'No existen Colecciones momentaneamente',
        newModalTitle: 'Crear nueva colección',
        parentHeading: 'Colección padre',
        tagsHeading: 'Tags',
        title: 'Colecciones',
        translationsHeading: 'Traducciones',
        add: 'Agregar',
        cancel: 'Cancelar',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'Este campo es obligatorio',
        name: 'Nombre',
        type: 'Tipo',
        subtitle: 'Subtitulo',
        content1: 'Esto es lo que hacemos: bla bla bla',
    }
};
