export default {
    en: {
        add: 'Add',
        cancel: 'Cancel',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'This field is required',
        name: 'Name',
        type: 'Type',
        category: 'Category',
        collection: 'Collection',
        enabledHeading: 'Enabled',
        homepage: 'Homepage',
        homepageFeatured: 'Homepage Featured',
        mainNavigation: 'Main Navigation',
        nameHeading: 'Name',
        new: 'New',
        newModalTitle: 'Add new collection',
        parentHeading: 'Parent Collection',
        tagsHeading: 'Tags',
        title: 'Grupos Comunes de Compras',
        translationsHeading: 'Translations',
        noResults: 'No collections yet',
        subtitle: 'Que es y como funciona:',
        content1: 'La idea es ofrecer a la comunidad un servicio nuevo online, de venta de frutas y verduras con entrega a domicilio con horario pactado y al mejor precio.  Esto es posible, organizando grupos de 15 personas interesadas en comprar y de esta forma, adquirir las frutas y verduras al mejor precio, asegurar el no desperdicio de las mismas y repartirlas entre los compradores.',
        buyers: 'Compradores',
        anotarse: 'Get in',
        desanotarse: 'Get out',
        proceder: 'Proceder',
        checkout: 'Finalizar',
        continueShopping: 'Continuar comprando',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        thanksModalText: 'Has ingresado al grupo. Ahora rellenaras la informacion de pago y envio, y cuando se complete el grupo te avisaremos por mail y mensaje. Gracias por la paciencia y la confianza!',
        anotadoModalTitle: 'Anotado!',
        grupoCompletoModalTitle: 'Grupo completo! Ingresa a otro grupo por favor.',
        login: 'Login',
        register: 'Register',
        cancel: 'Cancel',
    },
    es: {
        category: 'Categoría',
        collection: 'Colecciones',
        enabledHeading: 'Activada',
        homepage: 'Página Principal',
        homepageFeatured: 'Destacados en Página Principal',
        mainNavigation: 'Menú Principal',
        nameHeading: 'Nombre',
        new: 'Nuevo',
        noResults: 'No existen Colecciones momentaneamente',
        newModalTitle: 'Crear nueva colección',
        parentHeading: 'Colección padre',
        tagsHeading: 'Tags',
        title: 'Compras de Frutas y Verduras en Grupo',
        translationsHeading: 'Traducciones',
        add: 'Agregar',
        cancel: 'Cancelar',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'Este campo es obligatorio',
        name: 'Nombre',
        type: 'Tipo',
        subtitle: 'Que es y como funciona:',
        content1: 'La idea es ofrecer a la comunidad un servicio nuevo online, de venta de frutas y verduras con entrega a domicilio con horario pactado y al mejor precio.  Esto es posible, organizando grupos de 15 personas interesadas en comprar y de esta forma, adquirir las frutas y verduras al mejor precio, asegurar el no desperdicio de las mismas y repartirlas entre los compradores.',
        buyers: 'Compradores',
        proceder: 'Proceder',
        anotarse: 'Anotate',
        desanotarse: 'Desanotate',
        checkout: 'Finalizar',
        continueShopping: 'Continuar comprando',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        anotadoModalTitle: 'Anotado!',
        thanksModalText: 'Has ingresado al grupo de compra. Ahora rellenarás la información de pago y envío, y cuando se complete el grupo te avisaremos por mail y mensaje. Gracias por la paciencia y la confianza!',
        grupoCompletoModalTitle: 'Grupo completo! Ingresa a otro grupo por favor.',
        login: 'Loggearse',
        register: 'Registrarse',
        cancel: 'Cancelar',
    }
};
