export default {
    en: {
        add: 'Add',
        cancel: 'Cancel',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'This field is required',
        name: 'Name',
        type: 'Type',
        category: 'Category',
        collection: 'Collection',
        enabledHeading: 'Enabled',
        homepage: 'Homepage',
        homepageFeatured: 'Homepage Featured',
        mainNavigation: 'Main Navigation',
        nameHeading: 'Name',
        new: 'New',
        newModalTitle: 'Add new collection',
        parentHeading: 'Parent Collection',
        tagsHeading: 'Tags',
        title: 'Grupos Comunes de Compras',
        translationsHeading: 'Translations',
        noResults: 'No collections yet',
        subtitle: 'Que es y como funciona:',
        content1: 'La idea es ayudar a la comunidad organizando grupos de a 15/20 personas para comprar frutas/verduras al por mayor y repartirlas entre los compradores. Para esto necesito cierta información para crear una canasta básica de 10 o 15 productos que la gente generalmente consuma.',
        buyers: 'Compradores',
        anotarse: 'Get in',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        login: 'Login',
        register: 'Register',
        cancel: 'Cancel',
    },
    es: {
        category: 'Categoría',
        collection: 'Colecciones',
        enabledHeading: 'Activada',
        homepage: 'Página Principal',
        homepageFeatured: 'Destacados en Página Principal',
        mainNavigation: 'Menú Principal',
        nameHeading: 'Nombre',
        new: 'Nuevo',
        noResults: 'No existen Colecciones momentaneamente',
        newModalTitle: 'Crear nueva colección',
        parentHeading: 'Colección padre',
        tagsHeading: 'Tags',
        title: 'Compras de Frutas y Verduras en Grupo',
        translationsHeading: 'Traducciones',
        add: 'Agregar',
        cancel: 'Cancelar',
        fyv20: 'Frutas y verduras - grupo 20',
        fieldRequired: 'Este campo es obligatorio',
        name: 'Nombre',
        type: 'Tipo',
        subtitle: 'Que es y como funciona:',
        content1: 'La idea es ayudar a la comunidad organizando grupos de a 15/20 personas para comprar frutas/verduras al por mayor y repartirlas entre los compradores. Para esto necesito cierta información para crear una canasta básica de 10 o 15 productos que la gente generalmente consuma.',
        buyers: 'Compradores',
        anotarse: 'Anotarse',
        registerModalTitle: 'Para ingresar a la lista de grupos de compradores debes ingresar a tu cuenta.',
        login: 'Loggearse',
        register: 'Registrarse',
        cancel: 'Cancelar',
    }
};
