export default {
    en: {
        billingDetails: 'Billing Information',
        createdAt: 'Created at',
        customer: 'Customer',
        id: 'ID',
        nameHeading: 'Name',
        paymentMethod: 'Payment Method',
        priceHeading: 'Price',
        products: 'Products',
        quantityHeading: 'Qty.',
        shipping: 'Shipping',
        shippingCost: 'Shipping Cost',
        shippingDetails: 'Shipping Information',
        shippingMethod: 'Shipping Method',
        skuHeading: 'SKU',
        status: 'Status',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'VAT'
    },
    es: {
        billingDetails: 'Dados de facturacción',
        createdAt: 'Creada en',
        customer: 'Cliente',
        id: 'ID',
        nameHeading: 'Nombre',
        paymentMethod: 'Método de Pago',
        priceHeading: 'Precio',
        products: 'Productos',
        quantityHeading: 'Cantidad',
        shipping: 'Envío',
        shippingCost: 'Costo de Envío',
        shippingDetails: 'Datos de Envío',
        shippingMethod: 'Forma de Envío',
        skuHeading: 'SKU',
        status: 'Estado',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'IVA'
    }
};
