export default {
    en: {
        back: 'Back',
        delete: 'Delete item',
        categories: 'Categories',
        collections: 'Collections',
        currency: 'Currency',
        deleteProductModalTitle: 'You confirme the deletion?',
        description: 'Description',
        enabled: 'Enabled',
        fieldRequired: 'This field is required',
        homepage: 'Homepage',
        listPrice: 'List Price',
        mainCategory: 'Main Category',
        mainCollection: 'Main Collection',
        name: 'Name',
        pricing: 'Pricing',
        retailPrice: 'Retail Price',
        save: 'Save',
        sections: 'Featured in Sections',
        sku: 'SKU',
        stock: 'Stock',
        title: 'Edit Product',
        type: 'Type',
        vat: '% VAT (Included)'
    },
    es: {
        back: 'Volver',
        delete: 'Borrar item',
        categories: 'Categorias',
        collections: 'Colecciones',
        currency: 'Currency',
        deleteProductModalTitle: 'Confirma la eliminacion?',
        description: 'Descripción',
        enabled: 'Activo',
        fieldRequired: 'Este campo es obligatorio',
        homepage: 'Página Principal',
        listPrice: 'Lista de Precios',
        mainCategory: 'Categoria Principal',
        mainCollection: 'Colección Principal',
        name: 'Nombre',
        pricing: 'Precio',
        retailPrice: 'Precio Final',
        save: 'Guardar',
        sections: 'Destacados en Secciones',
        sku: 'SKU',
        stock: 'Stock',
        title: 'Editar Producto',
        type: 'Tipo',
        vat: '% IVA (Incluído)'
    }
};
